import type { Product, Category, ProcessStep } from './types';

export const socialLinks = {
  facebook: 'https://www.facebook.com/moortiindia23',
  instagram: 'https://www.instagram.com/marblehome_india/',
  twitter: 'https://twitter.com/moorti_india',
  youtube: 'https://www.youtube.com/@moortiindia',
  whatsapp: 'https://wa.me/919958476169'
};

export const categories: Category[] = [
  {
    id: '1',
    slug: 'ganesh',
    name: 'Marble Ganesh Statues',
    image: '/uploads/hero_ganesh.png',
    description: 'Handcrafted Ganesha idols in pure Makrana marble — from intimate home temple sizes to grand temple installations.',
    count: 24,
  },
  {
    id: '2',
    slug: 'radha-krishna',
    name: 'Radha Krishna',
    image: '/uploads/product_radha_krishna.png',
    description: 'Divine love immortalised in white marble — exquisitely carved Radha Krishna statues for home and temple.',
    count: 18,
  },
  {
    id: '3',
    slug: 'durga',
    name: 'Durga Maa',
    image: '/uploads/product_durga.png',
    description: 'Powerful and intricate Durga Maa statues, hand-carved with all ten arms and divine weapons.',
    count: 15,
  },
  {
    id: '4',
    slug: 'hanuman',
    name: 'Hanuman',
    image: '/uploads/product_hanuman.png',
    description: 'Majestic Hanuman Ji statues in pure white marble, capturing divine strength and unwavering devotion.',
    count: 12,
  },
  {
    id: '5',
    slug: 'buddha',
    name: 'Buddha Statues',
    image: '/uploads/product_buddha.png',
    description: 'Serene Buddha statues in pure white marble — from meditating Buddhas to Laughing Buddha designs.',
    count: 16,
  },
  {
    id: '6',
    slug: 'laxmi',
    name: 'Laxmi Maa',
    image: '/uploads/product_laxmi.png',
    description: 'Goddess Laxmi statues radiating prosperity and grace, carved from the finest Makrana marble.',
    count: 14,
  },
  {
    id: '7',
    slug: 'temples',
    name: 'Marble Temples',
    image: '/uploads/product_temple.png',
    description: 'Custom marble mandirs and temples — from compact home shrines to grand temple structures.',
    count: 20,
  },
  {
    id: '8',
    slug: 'garden',
    name: 'Garden Sculptures',
    image: '/uploads/category_garden.png',
    description: 'Elegant marble sculptures for gardens, courtyards, and outdoor spaces. Fountains, animals, and decorative pieces.',
    count: 22,
  },
];

export const featuredProducts: Product[] = [
  {
    id: '1',
    slug: 'radha-krishna-classic',
    name: 'Radha Krishna — Classic Pose',
    category: 'Radha Krishna',
    categorySlug: 'radha-krishna',
    image: '/uploads/product_radha_krishna.png',
    material: 'Makrana White Marble',
    godName: 'Radha Krishna',
    height: '24 inches',
    baseWidthDepth: '12 x 8 inches',
    weight: '35 kg',
    painting: 'Subtle Gold Highlights',
    shippingInfo: 'This price includes free ground shipping in India. Please contact us for a quote for International shipping.',
    productCare: 'Gently wipe with a soft dry cloth. Do not use acidic or harsh chemical cleaners. Keep away from direct extreme weather to preserve the natural polish.',
    whyChooseUs: 'Moorti India has been crafting Premium Handcrafted Marble Sculptures for Home/temples since 1985 in Jaipur. Our master artisans use only pure Makrana marble.',
    shortDesc: 'The divine couple in timeless marble — Krishna playing flute, Radha in graceful accompaniment.',
    description: 'This exquisite Radha Krishna statue is hand-carved from premium Makrana white marble by our master artisans in Jaipur. The divine couple is depicted in a classic pose — Krishna playing the flute with Radha standing in graceful adoration.',
    isFeatured: true,
    tags: ['Best seller', 'Premium'],
    finish: 'Smooth / Polished',
    color: 'Natural White',
    images: ['/uploads/product_radha_krishna.png', '/uploads/product_radha_krishna.png', '/uploads/product_radha_krishna.png', '/uploads/product_radha_krishna.png'],
  },
  {
    id: '7',
    slug: 'black-marble-ganesh-statue',
    name: 'Black Marble Ganesh Statue',
    category: 'Ganesh Statues',
    categorySlug: 'ganesh',
    image: '/uploads/hero_ganesh.png',
    material: 'Black Marble',
    godName: 'Ganesh',
    height: '26 inches',
    baseWidthDepth: '20 x 14 inches',
    weight: '55 kg',
    painting: 'Elegant Gold',
    shippingInfo: 'This price includes free ground shipping in India. Please contact us for a quote for International shipping.',
    productCare: 'Wipe with a soft, damp microfiber cloth. Avoid sharp objects near the elegant gold painting to prevent scratching.',
    whyChooseUs: 'We manufacture and export all kinds of marble murti. Handcrafted in Jaipur with high standards for quality and design.',
    shortDesc: 'A remarkable reclining Ganesh statue carved from solid black marble with silver and gold accents.',
    description: 'Inspired by the most premium modern art designs, this Black Marble Ganesh Statue brings a sense of grounded majesty to any space. The exquisite gold painting contrasts perfectly with the polished black stonework.',
    isFeatured: true,
    tags: ['New', 'Premium'],
    finish: 'Smooth / Polished',
    color: 'Black',
    images: ['/uploads/hero_ganesh.png', '/uploads/hero_ganesh.png', '/uploads/hero_ganesh.png', '/uploads/hero_ganesh.png'],
  },
  {
    id: '2',
    slug: 'durga-maa-traditional',
    name: 'Durga Maa — Ten Armed',
    category: 'Durga Maa',
    categorySlug: 'durga',
    image: '/uploads/product_durga.png',
    material: 'Makrana White Marble',
    godName: 'Durga Mata',
    height: '36 inches',
    baseWidthDepth: '24 x 16 inches',
    weight: '85 kg',
    painting: 'Vibrant Traditional',
    shippingInfo: 'This price includes free ground shipping in India. Please contact us for a quote for International shipping.',
    productCare: 'Clean only with a soft dry cloth. Keep away from moisture to protect the traditional painting details.',
    whyChooseUs: 'Every idol from Moorti India represents decades of ancestral craftsmanship from the heart of Rajasthan.',
    shortDesc: 'The supreme goddess in her full glory — ten-armed and seated upon a roaring lion.',
    description: 'Our Durga Maa statue captures the divine power and grace of the supreme goddess. Carved from pure Makrana marble, this ten-armed Durga is depicted seated upon her lion vahana in a commanding pose.',
    isFeatured: true,
    tags: ['Premium'],
    finish: 'Smooth / Polished',
    color: 'Natural White',
    images: ['/uploads/product_durga.png', '/uploads/product_durga.png', '/uploads/product_durga.png', '/uploads/product_durga.png'],
  },
  {
    id: '3',
    slug: 'hanuman-standing',
    name: 'Hanuman Ji — Standing',
    category: 'Hanuman',
    categorySlug: 'hanuman',
    image: '/uploads/product_hanuman.png',
    material: 'Makrana White Marble',
    godName: 'Hanuman',
    height: '48 inches',
    baseWidthDepth: '20 x 18 inches',
    weight: '120 kg',
    painting: 'Aesthetic Gold detailing',
    shippingInfo: 'This price includes free ground shipping in India. Please contact us for a quote for International shipping.',
    productCare: 'Wipe down regularly with a dry cloth. Protect from extreme heat to maintain the marble luster.',
    whyChooseUs: 'We use premium single-block Makrana stone for maximum structural integrity and spiritual purity.',
    shortDesc: 'Lord Hanuman in powerful standing pose, carrying the Sanjeevani mountain.',
    description: 'More than just a sculpture, this Hanuman Ji idol represents शक्ति (strength), भक्ति (devotion), and सुरक्षा (protection). Designed for modern homes and sacred spaces, it adds both spiritual energy and timeless elegance to your surroundings.',
    isFeatured: true,
    tags: ['Best seller', 'Premium'],
    finish: 'Smooth / Polished',
    color: 'Natural White',
    images: ['/uploads/product_hanuman.png', '/uploads/product_hanuman.png', '/uploads/product_hanuman.png', '/uploads/product_hanuman.png'],
  },
  {
    id: '4',
    slug: 'meditating-buddha',
    name: 'Buddha — Padmasana Meditation',
    category: 'Buddha Statues',
    categorySlug: 'buddha',
    image: '/uploads/product_buddha.png',
    material: 'Vietnam White Marble',
    godName: 'Gautam Buddha',
    height: '24 inches',
    baseWidthDepth: '18 x 14 inches',
    weight: '40 kg',
    painting: 'Natural Finish',
    shippingInfo: 'This price includes free ground shipping in India. Please contact us for a quote for International shipping.',
    productCare: 'Occasional wiping with a damp cloth keeps the natural Vietnam marble looking pristine.',
    whyChooseUs: 'Our Buddha statues are carved by specialized artisans focusing entirely on bringing absolute serenity to the facial features.',
    shortDesc: 'Complete stillness and inner peace captured in pure white marble.',
    description: 'Our meditating Buddha statue embodies the essence of inner peace and enlightenment. Carved from fine Vietnam white marble, the Buddha is depicted in Padmasana.',
    isFeatured: true,
    tags: ['Premium'],
    finish: 'Smooth / Polished',
    color: 'Natural White',
    images: ['/uploads/product_buddha.png', '/uploads/product_buddha.png', '/uploads/product_buddha.png', '/uploads/product_buddha.png'],
  },
  {
    id: '5',
    slug: 'laxmi-maa-standing',
    name: 'Laxmi Maa — Standing on Lotus',
    category: 'Laxmi Maa',
    categorySlug: 'laxmi',
    image: '/uploads/product_laxmi.png',
    material: 'Makrana White Marble',
    godName: 'Laxmi Mata',
    height: '30 inches',
    baseWidthDepth: '14 x 14 inches',
    weight: '45 kg',
    painting: 'Traditional Gold & Colours',
    shippingInfo: 'This price includes free ground shipping in India. Please contact us for a quote for International shipping.',
    productCare: 'Gently wipe the gold-painted areas to avoid wearing down the polish over the years.',
    whyChooseUs: 'Each Laxmi Maa statue is crafted following strict traditional guidelines to ensure spiritual perfection and prosperity.',
    shortDesc: 'Goddess of prosperity standing upon a lotus, blessing devotees with abundance.',
    description: 'This magnificent Laxmi Maa statue depicts the goddess of wealth and prosperity in her iconic standing pose atop a full-bloom lotus.',
    isFeatured: true,
    tags: ['Best seller', 'Premium'],
    finish: 'Smooth / Polished',
    color: 'Natural White',
    images: ['/uploads/product_laxmi.png', '/uploads/product_laxmi.png', '/uploads/product_laxmi.png', '/uploads/product_laxmi.png'],
  }
];

export const processSteps: ProcessStep[] = [
  {
    step: 1,
    title: 'Stone Selection',
    description: 'We source only the finest Makrana and Vietnam white marble — the same quarries used to build the Taj Mahal. Each block is hand-inspected for purity, grain, and quality.',
    icon: '◆',
    image: '/images/process_stone_selection.webp',
  },
  {
    step: 2,
    title: 'Master Carving',
    description: 'Our master artisans, trained in generations of traditional Jaipur stone carving, hand-chisel every sculpture. Each piece takes weeks to months to complete.',
    icon: '✦',
    image: '/images/process_master_carving.webp',
  },
  {
    step: 3,
    title: 'Mirror Polishing',
    description: 'A painstaking multi-stage polishing process transforms raw carved marble into a luminous, mirror-finish sculpture. The result is a piece that glows with inner light.',
    icon: '◈',
    image: '/images/process_mirror_polishing.webp',
  },
  {
    step: 4,
    title: 'Quality Inspection',
    description: 'Every sculpture undergoes a rigorous quality check — examining proportions, surface finish, and spiritual accuracy before it is approved for delivery.',
    icon: '◉',
    image: '/images/process_quality_inspection.webp',
  },
  {
    step: 5,
    title: 'Secure Packaging',
    description: 'We use export-grade wooden crating with custom foam insets and protective wrapping to ensure your sculpture arrives in perfect condition, anywhere in the world.',
    icon: '◍',
    image: '/images/process_secure_packaging.webp',
  },
  {
    step: 6,
    title: 'Worldwide Delivery',
    description: 'We ship to over 50 countries including Australia, USA, UK, Canada, UAE, and Singapore. Full tracking, insurance, and dedicated support throughout the journey.',
    icon: '◎',
    image: '/images/process_worldwide_delivery.webp',
  },
];

export const stats = [
  { value: 40, suffix: '+', label: 'Years of Craft' },
  { value: 10000, suffix: '+', label: 'Statues Created' },
  { value: 50, suffix: '+', label: 'Countries Reached' },
  { value: 100, suffix: '%', label: 'Handcrafted' },
];

export const navCategories = [
  { name: 'Ganesh Statues', slug: 'ganesh' },
  { name: 'Radha Krishna', slug: 'radha-krishna' },
  { name: 'Durga Maa', slug: 'durga' },
  { name: 'Hanuman Ji', slug: 'hanuman' },
  { name: 'Laxmi Maa', slug: 'laxmi' },
  { name: 'Buddha', slug: 'buddha' },
  { name: 'Marble Temples', slug: 'temples' },
  { name: 'Garden Sculptures', slug: 'garden' },
  { name: 'Ram Darbar', slug: 'ram-darbar' },
  { name: 'Saraswati Maa', slug: 'saraswati' },
  { name: 'Sai Baba', slug: 'sai-baba' },
  { name: 'Human Busts', slug: 'human-busts' },
];
